### ISSUE TITLE
Voice Channel Leave Bug

### ISSUE THREAD

**Issue by ISkylakeS** [KabyBot/KabyBot#1]
**TODO**: fix bug where when member leaves non-empty voice channel music stops

**Comment by ohlookitsAugust** [comment]
same but maybe I can fix it..?

**Comment by ISkylakeS** [comment]
I'll be very grateful.

**Comment by OpticFusion1** [comment]
Add a check to see if there are other users still in the channel, if there's still other users, don't close the audio connecion, from what i can see, it stops the audio connection as long as the user is correct, completely ignoring if there's still anyone else in the sever

**Comment by ISkylakeS** [comment]
@OpticFusion1 There's same check. If only KabyBot in the voice channel, it leaves, it's okay. But the problem is when user leaves non-empty channel bot doesn't leave channel but pauses current track.

**Comment by OpticFusion1** [comment]
@ISkylakeS okay, yea just noticed the check.
event.getGuild().getAudioManager().closeAudioConnection();
I believe this just pauses the current track in your case, i can't really check due to lack of documentation. however i assume you'll have to force the bot to leave if you'd want it to, otherwise it will just pause it, i could be wrong, but without having finished javadocs it's just a pain to figure out without testing

**Comment by OpticFusion1** [comment]
actually

public void onGuildVoiceLeave(GuildVoiceLeaveEvent event) {
        GuildMusicManager musicManager = getGuildAudioPlayer(event.getGuild());
        if (event.getGuild().getSelfMember().getVoiceState().inVoiceChannel()) {
            List<Member> members = event.getGuild().getSelfMember().getVoiceState().getChannel().getMembers();
            if (members.stream().allMatch(event.getGuild().getSelfMember()::equals)) {
                event.getGuild().getAudioManager().closeAudioConnection();
            }
        }
}

This gets called by anyone that leaves a voice chat, Gets the GuildMusicManager, checks if the bot is in the channel and if it is it loops through everyone in it until it finds the bot, then closes the AudioConnection, you'll want a size check or something to see how many users are in the VC

**Comment by ISkylakeS** [comment]
Afaik, Stream#allMatch returns true only if the list completely coincides with the specified condition

**Comment by OpticFusion1** [comment]
of course it was an obvious answer xD

**Comment by ISkylakeS** [comment]
Oh, shitty auto-closes

**Comment by ISkylakeS** [comment]
FIIXEEDD

**Comment by ISkylakeS** [comment]
forgot about EventListener.java

**Comment by ISkylakeS** [comment]
Ok, that's all
